default_stages:
  - commit
repos:
  - hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: name-tests-test
    repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
  - hooks:
      - id: black
    repo: https://github.com/psf/black
    rev: 23.1.0
  - hooks:
      - args:
          - --ignore=E501,E203,W503
        id: flake8
    repo: https://github.com/pycqa/flake8
    rev: 6.0.0
  - hooks:
      - id: pyupgrade
        args: ['--py310-plus']
    repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.1.1
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [feat, fix, ci, chore, test, build, docs, perf, refactor, style]
  - hooks:
      - id: commitizen
    repo: https://github.com/commitizen-tools/commitizen
    rev: v2.42.1

default_install_hook_types:
  - pre-commit
  - commit-msg
