"""create models

Revision ID: e268e1abda81
Revises:
Create Date: 2023-03-31 10:38:06.533730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e268e1abda81"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drone",
        sa.Column("serial_number", sa.String(length=100), nullable=False),
        sa.Column(
            "model",
            sa.Enum(
                "LIGHTWEIGHT",
                "MIDDLEWEIGHT",
                "CRUISERWEIGHT",
                "HEAVYWEIGHT",
                name="models",
            ),
            nullable=False,
        ),
        sa.Column("weight_limit", sa.Integer(), nullable=False),
        sa.Column("battery_capacity", sa.Integer(), nullable=False),
        sa.Column(
            "state",
            sa.Enum(
                "IDLE",
                "LOADING",
                "LOADED",
                "DELIVERING",
                "DELIVERED",
                "RETURNING",
                name="status",
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("drone_pkey")),
        sa.UniqueConstraint("serial_number", name=op.f("drone_serial_number_key")),
    )
    op.create_table(
        "medication",
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("weight", sa.Integer(), nullable=False),
        sa.Column("code", sa.String(), nullable=False),
        sa.Column("image", sa.String(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("medication_pkey")),
        sa.UniqueConstraint("code", name=op.f("medication_code_key")),
    )
    op.create_table(
        "load",
        sa.Column("origin", sa.String(length=100), nullable=True),
        sa.Column("destination", sa.String(length=100), nullable=True),
        sa.Column("create", sa.DateTime(), nullable=False),
        sa.Column("drone_id", sa.Integer(), nullable=False),
        sa.Column("weight_loaded", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["drone_id"],
            ["drone.id"],
            name=op.f("load_drone_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("load_pkey")),
    )
    op.create_table(
        "load_medication",
        sa.Column("load_id", sa.Integer(), nullable=False),
        sa.Column("medication_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["load_id"],
            ["load.id"],
            name=op.f("load_medication_load_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["medication_id"],
            ["medication.id"],
            name=op.f("load_medication_medication_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "load_id", "medication_id", name=op.f("load_medication_pkey")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("load_medication")
    op.drop_table("load")
    op.drop_table("medication")
    op.drop_table("drone")
    # ### end Alembic commands ###
